service: sendgrid-webhook-to-mixpanel-lambda

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  profile: weilandia

functions:
  app:
    handler: index.handler
    events:
      - http: 'POST /mixpanel_sendgrid_event'
